# ========================================================= #
#    Plugin KiemSoatDropMMOItems v1.1 by Hoàng           #
# ========================================================= #
# Day la file cau hinh chinh. Ban co the bat/tat cac tinh nang tai day.
# De xem huong dan chi tiet va ma nguon, truy cap: https://github.com/AI-Helper-Code-Bot/KiemSoatDropMMOItems

settings:
  # Bat/Tat tinh nang kiem tra block do nguoi choi dat.
  # Neu 'true', block nguoi choi dat (vi du: dat 1 khúc gỗ rồi đập) se khong roi ra item tu MMOItems.
  # Neu 'false', tat tinh nang nay va cho phep drop binh thuong.
  check-player-placed-blocks: true

  # Bat/Tat tinh nang kiem tra do lon cua cay trong.
  # Neu 'true', cay trong (lúa, cà rốt...) phai lon toi da (chin) moi roi ra item tu MMOItems.
  # Neu 'false', tat tinh nang nay.
  check-crop-growth: true

  # (Nang cao) Danh sach cac loai block duoc mien tru kiem tra.
  exempt-blocks: []

# Thong diep cua plugin, ho tro ma mau (&a, &b, &c...)
messages:
  prefix: "&e&l[KS-Drop] &r"
  reload-success: "&aDa tai lai cau hinh thanh cong!"
  no-permission: "&cBan khong co quyen su dung lenh nay."
  invalid-command: "&cLenh khong hop le. Su dung /ksdrop reload."