name: KiemSoatDropMMOItems
version: '${project.version}'
main: com.github.kiemsoatdrop.KiemSoatDropMMOItems
api-version: '1.20'
author: AI Helper (Fixed by v1.1)
description: Kiem soat drop item tu MMOItems de chong farm bug.

# Quan trọng: Đảm bảo plugin này được load SAU MMOItems và MythicLib
depend: [MMOItems, MythicLib]

commands:
  ksdrop:
    description: Lenh quan ly cua plugin KiemSoatDropMMOItems.
    usage: /ksdrop reload
    permission: ksdrop.admin
    aliases: [kiemsoatdrop]

permissions:
  ksdrop.admin:
    description: Cho phep su dung lenh /ksdrop reload.
    default: op